[package]
name = "ahc028"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
petgraph = "0.6.4"
proconio = { version = "0.4.3", features = ["derive"] }
superslice = "1.0.0"
